# Dockerfile.dev

FROM node:24-alpine

WORKDIR /app

COPY package.json package-lock.json ./

# Install dependencies (dev deps included)
RUN npm install

# Copy source code
COPY . .

# Expose Vite dev server port
EXPOSE 5173

# Start Vite dev server
CMD ["npm", "run", "dev", "--", "--host"]
